### ISSUE TITLE
Support AWS auth besides AWS_PROFILE.

### ISSUE THREAD

**Issue by ryan-roemer** [architect/utils#26] opened 2019-09-13 23:05 UTC
**Is your feature request related to a problem? Please describe.**
I use the wonderful [aws-vault](https://github.com/99designs/aws-vault) to keep my AWS client/secret keys encrypted and only decrypted in-memory, temporarily when absolutely needed.

This allows me to avoid putting secrets on-disk in a potentially risky way via the usual `AWS_PROFILE` means. (E.g., a malicious npm package could read from disk, etc.)

Problem is that `aws-vault` explicitly unsets `AWS_PROFILE` in the environment and instead uses [env vars](https://github.com/99designs/aws-vault#security) including:

```
$ aws-vault exec home -- env | grep AWS
AWS_VAULT=home
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=%%%
AWS_SECRET_ACCESS_KEY=%%%
AWS_SESSION_TOKEN=%%%
AWS_SECURITY_TOKEN=%%%
```

**Describe the solution you'd like**
In addition to `AWS_PROFILE`, I'd love to see support for the env var combination of `AWS_ACCESS_KEY_ID` + `AWS_SECRET_ACCESS_KEY` (and possibly some other of those env vars but I don't _think_ so?)

If it's just those two, then extra support should be (theoretically) super easy and straightforward to apply.

**Describe alternatives you've considered**
There are no alternatives because `aws-vault` unsets `AWS_PROFILE` and `architect/deploy` does this: https://github.com/architect/deploy/blob/5f9ef44d2632887bc36c6085f6fce08a3b05708a/src/validate/index.js#L36-L37

and then `architect/utils` further does this: https://github.com/architect/utils/blob/dafd689a9ce5dabe2db56ad0b996721003e59034/init-aws.js#L30-L42

```js
      if (process.env.AWS_PROFILE) {
        aws.config.credentials = new aws.SharedIniFileCredentials({
          profile: process.env.AWS_PROFILE
        })
      }
      else {
        // jic fallback to default creds (if specified)
        aws.config.credentials = new aws.SharedIniFileCredentials()
      }
      if (!aws.config.credentials.accessKeyId) {
        console.log(chars.err, 'Warning: missing or invalid AWS credentials file')
      }
    }
```

... and it seems this latter code could be amended to separately allow client + secret key with something like [`new aws.EnvironmentCredentials()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EnvironmentCredentials.html#constructor-property) which I think could just straight up work... (?)

... at any rate, would ❤️ to see this support as `aws-vault` is already part of all our AWS / Serverless workflows and would love to add it to our Architect best practices as we start investigating the framework more!

**Comment by ryanblock** [comment] 2019-12-26 04:05
@ryan-roemer good news, this is (finally) fixed in Architect 6.0.29 (RC out now – didn't want to do a proper production release today for obvious reasons). `npm i @architect/architect@RC`

**Comment by ryan-roemer** [comment] 2019-12-26 04:16
Thanks! Haven't had a chance to try out yet, but looking at this:

https://github.com/architect/utils/pull/45/files#diff-d4be9f9dd7c31a8b5335b051528b49e3R25-R47

there's an issue in that users of `aws-vault` **will** often pair the secrets not in creds with actual `.aws/credentials` files (they're just empty or like):

```
$ cat ~/.aws/credentials 

[profile default]
```

What I'd ❤️  to see is just a simple check for `process.env.AWS_ACCESS_KEY_ID` and `process.env.AWS_SECRET_ACCESS_KEY` _first_ and then back to file system second.

Or, just let the user specify `ARC_AWS_CREDS=env` from shell.

Thanks!

**Comment by ryan-roemer** [comment] 2019-12-26 05:57
Here's a stab at some completely untested (and thus mostly pseudo-) code that is more in line of how I could see something really working well with `aws-vault` and folks who really want to minimize the secrets stored on disk:

```js
module.exports = function initAWS ({arc, needsValidCreds=true}) {
  // AWS SDK intentionally not added to package deps; assume caller already has it
  // eslint-disable-next-line
  let aws = require('aws-sdk')

  try {
    arc.aws = arc.aws || []
    let region = arc.aws.find(e=> e[0] === 'region')
    process.env.AWS_REGION = region && region[1] ||
                             process.env.AWS_REGION

    // Check env first.
    let hasEnvVars = process.env.AWS_ACCESS_KEY_ID &&
                     process.env.AWS_SECRET_ACCESS_KEY
    if (hasEnvVars) {
      process.env.ARC_AWS_CREDS = 'env'
      aws.config.credentials = new aws.Credentials({
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
      })
      credentialCheck()
    }
    // Check credentials next.
    else if (exists(join(homeDir, '.aws', 'credentials'))) {
      let profile = arc.aws.find(e=> e[0] === 'profile')
      process.env.ARC_AWS_CREDS = 'profile'
      process.env.AWS_PROFILE = profile && profile[1] ||
                                process.env.AWS_PROFILE ||
                                'default'
      aws.config.credentials = new aws.SharedIniFileCredentials({
        profile: process.env.AWS_PROFILE
      })
      credentialCheck()
    }

    function credentialCheck() {
      let creds = aws.config.credentials
      let noCreds = !creds || creds && !creds.accessKeyId
      if (noCreds && needsValidCreds) {
        // Set missing creds flag and let consuming modules handle as necessary
        process.env.ARC_AWS_CREDS = 'missing'
      }
      else if (noCreds && !needsValidCreds) {
        process.env.ARC_AWS_CREDS = 'dummy'
        aws.config.credentials = new aws.Credentials({
          accessKeyId: 'xxx',
          secretAccessKey: 'xxx'
        })
      }
      // Always unset profile to prevent misleading claims about loaded creds
      if (noCreds) {
        delete process.env.AWS_PROFILE
      }
    }
  }
  catch(e) {
    // Don't exit process here; caller should be responsible
    let update = updater('Startup')
    update.err(e)
  }
}
```

Don't know if that approach would be acceptable on your end, but it would be cool to see if we could just check `process.env.[AWS VARS]` first as that's also way less I/O expensive (not that configuration initialization has that much of a perf hit in the big picture).

At any rate, thanks for your work, and hope this suggestion helps think about the issue! 🙏

**Comment by ryanblock** [comment] 2019-12-26 06:39
The request def makes sense, I know folks do use the creds file for things other than the access ID and secret key. @brianleroux and I discussed earlier this week and decided that credentials file should win over env vars, but I like your approach of an override. Should be easy to add, will drop that in first thing tomorrow!

**Comment by apsoto** [comment] 2019-12-26 20:44
FYI, I want to point out another way to specify credentials.  I use a multi org AWS account and my primary AWS account grants access to the sub account which I use for dev work.  The AWS profile looks like this:
```
# Account in Root Account
[root]
aws_access_key_id = XXX
aws_secret_access_key = XXX
region = us-east-1
output = json

# Account sub-account
[sub]
role_arn = arn:aws:iam::111111111:role/asotoSTSRole
source_profile = root
region = us-east-1
```

Then I specify the sub account as my AWS_PROFILE
```
export AWS_PROFILE=sub
```

Therefore, checking for `accessKeyId` on the profile (sub) would fail the check even though the credentials are valid.

**Comment by ryanblock** [comment] 2019-12-27 00:27
@apsoto so then what would your ideal behavior be here?

**Comment by apsoto** [comment] 2019-12-27 02:06
The behavior I would expect is to *not warn* about an invalid profile when it is actually valid.  

I commented above because I wanted to let you know that checking for `accessKeyId` is not sufficient (at least in my case) because the accessKey is in the source profile.

Maybe instead of doing your own 'check'  leverage the AWS library to report validity by using the callback option:

https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/shared_ini_file_credentials.js#L56

**Comment by ryanblock** [comment] 2019-12-27 05:48
Perhaps you can help me better understand where the issue is @apsoto, as I don't use STS.

I tried specifying a `source_profile` that associates to a valid set of credentials, and then loaded that profile. No access key and secret key load into the AWS config object, so it would warn. But also, Architect operations would not execute, throwing the following error: ```CredentialsError: Missing credentials in config
    at SharedIniFileCredentials.load (/dir/architect/architect/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:144:11)
    at SharedIniFileCredentials.coalesceRefresh (/dir/architect/architect/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/dir/architect/architect/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:168:10)```

So it sounds to me more like you want

**Comment by ryanblock** [comment] 2019-12-27 05:58
@ryan-roemer that change here: https://github.com/architect/utils/pull/49/files wdyt?

**Comment by ryan-roemer** [comment] 2019-12-28 04:16
@ryanblock -- I think that looks good on inspection! I'll try to give it a whirl on Monday/early next week. Thanks for being so responsive to feedback!

**Closed** 2019-12-28 22:55 UTC

**Comment by ryanblock** [comment] 2019-12-28 22:57
Closing for now, @apsoto please do tell me more about your use case, sounds like something we should support! I may open a second issue for it. AWS creds init [is here](https://github.com/architect/utils/blob/master/banner/init-aws.js) and [tests are here](https://github.com/architect/utils/blob/master/test/banner/init-aws-test.js)

**Comment by apsoto** [comment] 2019-12-29 07:31
@ryanblock  I simply noticed there was a warning message printed when trying out the framework:

```
$ arc sandbox
× Warning: missing or invalid AWS credentials file
× Warning: missing or invalid AWS credentials file
         App ⌁ init
      Region ⌁ us-east-1
     Profile ⌁ sub
     Version ⌁ Architect 6.0.28
         cwd ⌁ /Users/asoto/projects/scratch/arc

✓ Sandbox Found Architect manifest, starting up
✓ Init process.env from .arc-env @testing
✓ Sandbox Project files hydrated into functions
✓ Sandbox Loaded routes
    get / ................................. get-index

✓ Sandbox Sandbox started in 452ms
✈︎ Local environment ready!

    http://localhost:3333
```

I knew the credentials were valid since I use them for lots of other projects, so I dug into the source code and noticed that it was checking if an aws access key existed or not.  

    https://github.com/architect/utils/blob/master/banner/init-aws.js#L64

The AWS sdk 'knows' to find the access key from the source profile not from the named profile.  I was just pointing out that the non-existance of the aws access key in the named profile is not an invalid configuration, and therefore, the message is misleading.

**Comment by apsoto** [comment] 2019-12-29 07:37
I updated the comment above with an actual deploy (initially I showed `sandbox`), just to show that the creds are valid when using multi-org credentials

**Comment by ryan-roemer** [comment] 2019-12-31 22:40
Trying out `@architect/architect@6.0.29-RC.0`.

First note:

```
$ arc sandbox
(node:51955) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `options` of 'undefined' or 'null'.
    at maybeCreate (/Users/rye/scm/fmd/aws-lambda-architect-reference/node_modules/@architect/architect/node_modules/@architect/create/src/bootstrap/index.js:18:46)
    at before (/Users/rye/scm/fmd/aws-lambda-architect-reference/node_modules/@architect/architect/src/before/index.js:6:3)
    at main (/Users/rye/scm/fmd/aws-lambda-architect-reference/node_modules/@architect/architect/src/index.js:82:7)
    at /Users/rye/scm/fmd/aws-lambda-architect-reference/node_modules/@architect/architect/src/index.js:97:11
    at Object.<anonymous> (/Users/rye/scm/fmd/aws-lambda-architect-reference/node_modules/@architect/architect/src/index.js:98:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
(node:51955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:51955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ryan-roemer** [comment] 2019-12-31 22:51
@ryanblock -- Can you do a new RC release? https://unpkg.com/browse/@architect/architect@6.0.29-RC.0/package.json has `@architect/utils@1.4.1` hard pinned so I can't easily test futher... Thanks!

**Comment by ryanblock** [comment] 2020-01-03 03:38
Sorry, been out of connectivity the last couple days. Will see if I'm able to cut a new release first thing tomorrow!

**Comment by ryanblock** [comment] 2020-01-03 22:14
Sorry, came down with something gnarly yesterday, I'm out of commission for a minute. Will check back asap!

**Comment by ryanblock** [comment] 2020-01-06 14:05
Quick update: `v1.4.3-RC.0` out as of a couple days ago (courtesy @defionscode)!

**Comment by ryanblock** [comment] 2020-01-06 22:17
@ryan-roemer I haven't been able to repro that destructuring failure you posted before, what was the .arc file (or repo if possible) you saw that with?

**Comment by ryan-roemer** [comment] 2020-01-07 00:34
I haven't had a chance to try `v1.4.3-RC.0` yet (thanks @defionscode !) and will report back then if I hit issues...

**Comment by ryanblock** [comment] 2020-01-07 22:15
Sounds good, it's now mainlined and released in `6.0.29`!

**Comment by ryan-roemer** [comment] 2020-01-08 00:15
@ryanblock Thanks for all your work. I'm pleased to report I can now deploy with `aws-vault`! 🎉

**Comment by ryanblock** [comment] 2020-01-08 00:17
My pleasure, thanks for your patience! And again, big hat tip to @defionscode for his shiny polish on this code path.
